platform :ios, '6.0'
xcodeproj 'iMapToy/iMapToy.xcodeproj'
pod 'ASIHTTPRequest', '~> 1.8.1'
pod 'BlockAlertsAnd-ActionSheets', '~> 1.0.6'
pod 'CocoaLumberjack', '~> 1.6.2'
pod 'ConciseKit', '~> 0.1.2'
pod 'Google-Maps-iOS-SDK', '~> 1.4.0'
pod 'JSONKit', '~> 1.5pre'
pod 'SVProgressHUD', '~> 0.9'
pod 'TSMessages', '~> 0.9.3'
